import Link from 'next/link';
import { PageIntro } from '@/components/common/page-intro';
import { PromptGrid } from '@/components/prompts/prompt-grid';
import { getCategories, getStyles } from '@/lib/repositories/content';
import { findPublishedPrompts } from '@/lib/repositories/prompts';

export const metadata = { title: 'AI Photo Prompts | OMRI Prompt' };
export default async function PromptsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const params = await searchParams; const [result, categories, styles] = await Promise.all([findPublishedPrompts(params), getCategories(), getStyles()]);
  return <PageIntro eyebrow="PROMPT LIBRARY" title="All AI Photo Prompts" description="Search, filter, and copy thoughtfully crafted prompts."><form className="filter-bar prompt-filter" aria-label="Filter prompts"><label className="sr-only" htmlFor="prompt-library-search">Search prompts</label><input id="prompt-library-search" name="q" defaultValue={params.q} placeholder="Search prompts"/><label className="sr-only" htmlFor="prompt-category">Filter by category</label><select id="prompt-category" name="category" defaultValue={params.category}><option value="">All categories</option>{categories.map((item) => <option value={item.slug} key={item.id}>{item.name}</option>)}</select><label className="sr-only" htmlFor="prompt-style">Filter by style</label><select id="prompt-style" name="style" defaultValue={params.style}><option value="">All styles</option>{styles.map((item) => <option value={item.slug} key={item.id}>{item.name}</option>)}</select><label className="sr-only" htmlFor="prompt-sort">Sort prompts</label><select id="prompt-sort" name="sort" defaultValue={params.sort}><option value="trending">Trending</option><option value="latest">Latest</option><option value="copied">Most copied</option><option value="views">Most viewed</option></select><button type="submit">Apply</button></form><p className="result-count">{result.total} prompt{result.total === 1 ? '' : 's'} found</p><PromptGrid items={result.items}/>{result.pages > 1 && <nav className="pagination" aria-label="Pagination">{Array.from({ length: result.pages }, (_, i) => <Link key={i} className={result.page === i + 1 ? 'active' : ''} href={{ query: { ...params, page: i + 1 } }}>{i + 1}</Link>)}</nav>}</PageIntro>;
}
