import Link from 'next/link';
import { LogoutButton } from '@/components/auth/logout-button';
import { SiteFooter, SiteHeader } from '@/components/common/site-chrome';
import { prisma } from '@/lib/prisma';
import { BrandLogo } from '@/components/common/brand';
export function PageIntro({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children?: React.ReactNode }) { return <><SiteHeader/><main className="route-page"><section className="route-intro"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p>{children}</section></main><SiteFooter/></>; }
export function AuthScreen({ title, description }: { title: string; description: string }) { return <main className="auth-screen"><Link className="brand" href="/" aria-label="OMRI Prompt home"><BrandLogo className="auth-logo-image" /></Link><div className="auth-card"><div className="eyebrow">OMRI PROMPT ACCOUNT</div><h1>{title}</h1><p>{description}</p></div></main>; }
const adminLinks = [['Overview','/admin'],['Prompts','/admin/prompts'],['Categories','/admin/categories'],['Styles','/admin/styles'],['Tags','/admin/tags'],['Users','/admin/users'],['Submissions','/admin/submissions'],['Images','/admin/images'],['Blog','/admin/blog'],['SEO','/admin/seo'],['Analytics','/admin/analytics'],['Ads','/admin/ads'],['Affiliate','/admin/affiliate'],['Premium','/admin/premium'],['Settings','/admin/settings'],['Homepage','/admin/homepage']];
export async function AdminScreen({ title, description, children }: { title: string; description: string; children?: React.ReactNode }) { const [prompts, users, views, copies, shares, favorites, submissions, clicks] = await Promise.all([prisma.prompt.count(), prisma.user.count(), prisma.promptView.count(), prisma.promptCopy.count(), prisma.promptShare.count(), prisma.favorite.count(), prisma.submission.count({ where: { status: 'PENDING' } }), prisma.affiliateClick.count()]); const stats = [['Total prompts', prompts],['Total users', users],['Total views', views],['Total copies', copies],['Total shares', shares],['Total favorites', favorites],['Pending submissions', submissions],['Affiliate clicks', clicks]]; return <main className="admin-shell"><aside><Link className="brand" href="/" aria-label="OMRI Prompt home"><BrandLogo className="admin-logo-image" /></Link><small>ADMIN CONTROL CENTER</small>{adminLinks.map(([label, href]) => <Link href={href} key={href}>{label}</Link>)}<LogoutButton/></aside><section className="admin-content"><div className="eyebrow">CONTENT OPERATIONS</div><h1>{title}</h1><p>{description}</p>{children ?? <div className="admin-stat-grid">{stats.map(([label, value]) => <div key={label}><small>{label}</small><b>{Number(value).toLocaleString()}</b>{Number(value) === 0 && <span>No data available yet.</span>}</div>)}</div>}</section></main>; }
