export type CatalogPrompt={title:string;slug:string;description:string;prompt:string;category:string;style:string;image:string;copies:string;createdAt:string};
export const catalog:CatalogPrompt[]=[
{title:'Cinematic Black Suit Portrait',slug:'cinematic-black-suit-male-portrait',description:'A powerful editorial portrait with cinematic contrast.',prompt:'Cinematic editorial portrait of a confident man in a tailored black suit, dramatic low-key studio lighting, 85mm lens, Sony A7 IV, rich shadows, realistic skin texture, 4:5',category:'Men',style:'Cinematic',image:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=85',copies:'8.2k',createdAt:'2026-09-12'},
{title:'Golden Hour Street Style',slug:'golden-hour-street-style',description:'Warm fashion photography at sunset.',prompt:'Editorial street style portrait at golden hour, natural sun flare, modern neutral tailoring, 35mm film look, authentic city texture, 4:5',category:'Fashion',style:'Editorial',image:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=85',copies:'6.4k',createdAt:'2026-09-10'},
{title:'Studio Beauty in Blue',slug:'studio-beauty-in-blue',description:'Clean high-end beauty portrait in a cobalt studio.',prompt:'High-end studio beauty portrait, cobalt blue seamless backdrop, softbox lighting, 85mm lens, luminous natural skin, fashion campaign composition, 4:5',category:'Women',style:'Studio',image:'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=85',copies:'5.8k',createdAt:'2026-09-09'},
{title:'Dreamy Summer Getaway',slug:'dreamy-summer-getaway',description:'An elevated summer holiday travel portrait.',prompt:'Dreamy coastal travel portrait, sun-washed Mediterranean architecture, linen outfit, candid editorial moment, soft color grading, realistic photography, 4:5',category:'Travel',style:'Realistic',image:'https://images.unsplash.com/photo-1496950866446-3253e1470e8e?auto=format&fit=crop&w=900&q=85',copies:'4.9k',createdAt:'2026-09-07'}];
export const categories=['Men','Women','Couples','Friends','Family','Wedding','Fashion','Luxury','Cars','Bikes','Travel','Fitness','Cinematic','Street Photography','Professional','Instagram','Profile Pictures','Traditional','Festival','Lifestyle','Nature','Business'];
export const styles=['Cinematic','Realistic','Studio','Vintage','Moody','Minimal','Editorial','Black & White','Street','Luxury','Fashion','Dramatic'];
export function findPrompt(slug:string){return catalog.find(p=>p.slug===slug)}
